<html>
<head>
<title>Soy_Nina_API REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>Soy_Nina_API REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Anotacion</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/anotacion/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/anotacion/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/anotacion/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/anotacion/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/anotacion/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Apoyo_Externo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/apoyo_externo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/apoyo_externo/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/apoyo_externo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/apoyo_externo/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/apoyo_externo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Area_Trabajo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/area_trabajo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/area_trabajo/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/area_trabajo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/area_trabajo/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/area_trabajo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Area_Voluntariado</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/area_voluntariado/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/area_voluntariado/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/area_voluntariado/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/area_voluntariado/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/area_voluntariado/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Asesor</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/asesor/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/asesor/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/asesor/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/asesor/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/asesor/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Asistencia_Evento</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/asistencia_evento/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/asistencia_evento/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/asistencia_evento/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/asistencia_evento/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/asistencia_evento/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Asistencia_Sororo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/asistencia_sororo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/asistencia_sororo/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/asistencia_sororo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/asistencia_sororo/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/asistencia_sororo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Centro_Academico</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/centro_academico/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/centro_academico/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/centro_academico/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/centro_academico/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/centro_academico/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ciclo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ciclo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ciclo/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ciclo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ciclo/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ciclo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Club</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/club/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/club/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/club/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/club/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/club/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Contacto_Emergencia</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/contacto_emergencia/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/contacto_emergencia/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/contacto_emergencia/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/contacto_emergencia/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/contacto_emergencia/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Detalle_Importante</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/detalle_importante/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/detalle_importante/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/detalle_importante/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/detalle_importante/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/detalle_importante/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Direccion</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/direccion/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/direccion/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/direccion/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/direccion/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/direccion/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Donacion</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/donacion/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/donacion/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/donacion/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/donacion/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/donacion/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Encargado</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/encargado/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/encargado/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/encargado/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/encargado/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/encargado/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Equipo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/equipo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/equipo/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/equipo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/equipo/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/equipo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Evento</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/evento/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/evento/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/evento/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/evento/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/evento/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Grado</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/grado/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/grado/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/grado/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/grado/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/grado/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Grado_Academico</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/grado_academico/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/grado_academico/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/grado_academico/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/grado_academico/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/grado_academico/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Informacion_Academica</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/informacion_academica/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/informacion_academica/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/informacion_academica/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/informacion_academica/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/informacion_academica/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Informacion_Socioeconomica</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/informacion_socioeconomica/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/informacion_socioeconomica/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/informacion_socioeconomica/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/informacion_socioeconomica/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/informacion_socioeconomica/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Miembro_Equipo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/miembro_equipo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/miembro_equipo/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/miembro_equipo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/miembro_equipo/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/miembro_equipo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ocupacion</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ocupacion/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ocupacion/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ocupacion/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ocupacion/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ocupacion/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Pais</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/pais/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/pais/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/pais/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/pais/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/pais/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Parentesco</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/parentesco/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/parentesco/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/parentesco/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/parentesco/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/parentesco/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Persona</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/persona/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/persona/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/persona/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/persona/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/persona/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Progenitores</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/progenitores/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/progenitores/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/progenitores/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/progenitores/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/progenitores/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Registro_Llamadas</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/registro_llamadas/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/registro_llamadas/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/registro_llamadas/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/registro_llamadas/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/registro_llamadas/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Rendimiento</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/rendimiento/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/rendimiento/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/rendimiento/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/rendimiento/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/rendimiento/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Rubro</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/rubro/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/rubro/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/rubro/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/rubro/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/rubro/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Telefono</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/telefono/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/telefono/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/telefono/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/telefono/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/telefono/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Tipo_Convivencia</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/tipo_convivencia/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/tipo_convivencia/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/tipo_convivencia/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/tipo_convivencia/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/tipo_convivencia/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Tipo_Detalle</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/tipo_detalle/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/tipo_detalle/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/tipo_detalle/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/tipo_detalle/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/tipo_detalle/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Tipo_Evento</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/tipo_evento/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/tipo_evento/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/tipo_evento/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/tipo_evento/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/tipo_evento/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Tipo_Moneda</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/tipo_moneda/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/tipo_moneda/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/tipo_moneda/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/tipo_moneda/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/tipo_moneda/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Tipo_Ocupacion</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/tipo_ocupacion/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/tipo_ocupacion/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/tipo_ocupacion/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/tipo_ocupacion/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/tipo_ocupacion/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Tipo_Persona</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/tipo_persona/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/tipo_persona/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/tipo_persona/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/tipo_persona/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/tipo_persona/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Transporte</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/transporte/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/transporte/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/transporte/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/transporte/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/transporte/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Usuario</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/usuario/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/usuario/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/usuario/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/usuario/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/usuario/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Valoracion</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/valoracion/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/valoracion/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/valoracion/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/valoracion/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/valoracion/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Voluntario</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/voluntario/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/voluntario/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/voluntario/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/voluntario/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/voluntario/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
